// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineShop.Data;

namespace OnlineShop.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnlineShop.Data.Product.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Test Description",
                            ImagePath = "/images/mobile_1.jpg",
                            Price = 300m,
                            ProductName = "Product 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Test Description",
                            ImagePath = "/images/mobile_2.jpg",
                            Price = 400m,
                            ProductName = "Product 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Test Description",
                            ImagePath = "/images/mobile_3.jpg",
                            Price = 500m,
                            ProductName = "Product 3"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Test Description",
                            ImagePath = "/images/mobile_4.jpg",
                            Price = 600m,
                            ProductName = "Product 4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
